// @vitest-environment jsdom
import { describe, it, expect, vi, afterEach, beforeAll } from 'vitest'
import { render, screen, cleanup, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { DocumentsScreen } from '../../src/renderer/screens/DocumentsScreen'
import { ChatScreen } from '../../src/renderer/screens/ChatScreen'
import { ToastProvider } from '../../src/renderer/components'
import { resetDocTaskStoreForTests } from '../../src/renderer/lib/doctasks'
import {
  DOC_TASK_BUSY_MESSAGE,
  type DocTaskStatus,
  type DocumentInfo,
  type DocumentSummary,
  type RuntimeStatus
} from '../../src/shared/types'
import { stubApi } from '../helpers/renderer'

// Phase 33 renderer tests: the Summarize row action + polling busy state, the summary
// display in the preview (attribution line, truncated note, Regenerate), the friendly
// failure, and the chat-during-task busy copy with its cancel option.

function doc(over: Partial<DocumentInfo> = {}): DocumentInfo {
  return {
    id: 'd1',
    title: 'contract.pdf',
    originalPath: '/u/contract.pdf',
    mimeType: 'application/pdf',
    sizeBytes: 2048,
    status: 'indexed',
    errorMessage: null,
    chunkCount: 7,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    ...over
  }
}

function summary(over: Partial<DocumentSummary> = {}): DocumentSummary {
  return {
    text: 'Key points: payment is due in 30 days; both parties may terminate.',
    modelId: 'qwen3-4b-q4',
    createdAt: '2026-06-11T10:00:00Z',
    truncated: false,
    ...over
  }
}

function task(over: Partial<DocTaskStatus> = {}): DocTaskStatus {
  return {
    jobId: 'j1',
    kind: 'summary',
    documentIds: ['d1'],
    state: 'running',
    progress: { stepsDone: 0, stepsTotal: 0 },
    error: null,
    resultRef: null,
    ...over
  }
}

const preview = {
  id: 'd1',
  title: 'contract.pdf',
  mimeType: 'application/pdf',
  segments: [{ text: 'the extracted body', pageNumber: 1, sectionLabel: null }]
}

beforeAll(() => {
  Object.defineProperty(window.HTMLElement.prototype, 'scrollTo', {
    configurable: true,
    writable: true,
    value: () => {}
  })
})

afterEach(() => {
  cleanup()
  resetDocTaskStoreForTests()
  vi.restoreAllMocks()
})

describe('DocumentsScreen — Summarize action (Phase 33)', () => {
  it('runs the polling flow: busy state with progress, then the summary opens in the preview', async () => {
    const user = userEvent.setup()
    let docs = [doc()]
    let status = task({ state: 'running', progress: { stepsDone: 1, stepsTotal: 3 } })
    const startDocTask = vi.fn(async () => ({ jobId: 'j1' }))
    const getDocTask = vi.fn(async () => status)
    const previewDocument = vi.fn(async () => preview)
    stubApi({
      listDocuments: vi.fn(async () => docs),
      startDocTask,
      getDocTask,
      previewDocument
    })
    render(<DocumentsScreen />)

    await screen.findByText('contract.pdf')
    await user.click(screen.getByRole('button', { name: /^summarize$/i }))
    expect(startDocTask).toHaveBeenCalledWith({ kind: 'summary', documentIds: ['d1'] })

    // Busy state with step progress, plus a cancel affordance, while polling reports running.
    expect(await screen.findByText(/Summarizing…\s*\(1\/3\)/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /^cancel$/i })).toBeInTheDocument()

    // The task finishes; the next poll sees it and the screen refreshes + opens the preview.
    docs = [doc({ summary: summary() })]
    status = task({
      state: 'done',
      progress: { stepsDone: 3, stepsTotal: 3 },
      resultRef: { documentId: 'd1' }
    })
    await waitFor(() => expect(previewDocument).toHaveBeenCalledWith('d1'), { timeout: 3000 })

    // The preview shows the summary section: text, attribution, Regenerate.
    expect(await screen.findByText(/payment is due in 30 days/)).toBeInTheDocument()
    expect(screen.getByText(/Generated by qwen3-4b-q4/)).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /regenerate/i })).toBeInTheDocument()
    // Busy state is gone; after closing the modal the row action reads "Summarize again".
    expect(screen.queryByText(/Summarizing…/)).not.toBeInTheDocument()
    await user.keyboard('{Escape}')
    expect(await screen.findByRole('button', { name: /summarize again/i })).toBeInTheDocument()
  })

  it('cancelling the busy task calls cancelDocTask', async () => {
    const user = userEvent.setup()
    const cancelDocTask = vi.fn(async () => {})
    stubApi({
      listDocuments: vi.fn(async () => [doc()]),
      startDocTask: vi.fn(async () => ({ jobId: 'j1' })),
      getDocTask: vi.fn(async () => task({ state: 'running' })),
      cancelDocTask
    })
    render(<DocumentsScreen />)
    await screen.findByText('contract.pdf')
    await user.click(screen.getByRole('button', { name: /^summarize$/i }))
    await user.click(await screen.findByRole('button', { name: /^cancel$/i }))
    expect(cancelDocTask).toHaveBeenCalled()
  })

  it('shows the friendly failure copy when the task fails', async () => {
    const user = userEvent.setup()
    stubApi({
      listDocuments: vi.fn(async () => [doc()]),
      startDocTask: vi.fn(async () => ({ jobId: 'j1' })),
      getDocTask: vi.fn(async () =>
        task({ state: 'failed', error: 'No AI model is running. Open the AI Model screen and start one first.' })
      )
    })
    render(<DocumentsScreen />)
    await screen.findByText('contract.pdf')
    await user.click(screen.getByRole('button', { name: /^summarize$/i }))
    expect(
      await screen.findByText(/No AI model is running/i, undefined, { timeout: 3000 })
    ).toBeInTheDocument()
  })

  it('surfaces the backend refusal (e.g. answer streaming) as the error banner', async () => {
    const user = userEvent.setup()
    stubApi({
      listDocuments: vi.fn(async () => [doc()]),
      startDocTask: vi.fn(async () => {
        throw new Error('An answer is being written right now. Wait for it to finish (or stop it), then try again.')
      })
    })
    render(<DocumentsScreen />)
    await screen.findByText('contract.pdf')
    await user.click(screen.getByRole('button', { name: /^summarize$/i }))
    expect(await screen.findByText(/answer is being written/i)).toBeInTheDocument()
  })

  it('Preview shows an existing summary with attribution; Regenerate starts a new task', async () => {
    const user = userEvent.setup()
    const startDocTask = vi.fn(async () => ({ jobId: 'j2' }))
    stubApi({
      listDocuments: vi.fn(async () => [doc({ summary: summary() })]),
      previewDocument: vi.fn(async () => preview),
      startDocTask,
      getDocTask: vi.fn(async () => task({ state: 'running', jobId: 'j2' }))
    })
    render(<DocumentsScreen />)
    await screen.findByText('contract.pdf')
    // The row flags the stored summary.
    expect(screen.getByText('Summary')).toBeInTheDocument()

    await user.click(screen.getByRole('button', { name: /^preview$/i }))
    expect(await screen.findByText(/payment is due in 30 days/)).toBeInTheDocument()
    expect(screen.getByText(/Generated by qwen3-4b-q4/)).toBeInTheDocument()

    await user.click(screen.getByRole('button', { name: /regenerate/i }))
    expect(startDocTask).toHaveBeenCalledWith({ kind: 'summary', documentIds: ['d1'] })
  })

  it('shows the honest truncation note for a long document (the map-call ceiling)', async () => {
    const user = userEvent.setup()
    stubApi({
      listDocuments: vi.fn(async () => [doc({ summary: summary({ truncated: true }) })]),
      previewDocument: vi.fn(async () => preview)
    })
    render(<DocumentsScreen />)
    await screen.findByText('contract.pdf')
    await user.click(screen.getByRole('button', { name: /^preview$/i }))
    expect(await screen.findByText(/covers its beginning/i)).toBeInTheDocument()
  })

  it('offers no Summarize action for unready documents', async () => {
    stubApi({
      listDocuments: vi.fn(async () => [
        doc({ status: 'failed', errorMessage: 'nope', chunkCount: 0 })
      ])
    })
    render(<DocumentsScreen />)
    await screen.findByText('contract.pdf')
    expect(screen.queryByRole('button', { name: /^summarize$/i })).not.toBeInTheDocument()
  })
})

describe('ChatScreen — chat during a document task (D26 friendly copy)', () => {
  const runningStatus: RuntimeStatus = {
    running: true,
    modelId: 'm1',
    port: 1234,
    healthy: true,
    message: 'ok'
  }

  it('shows the shared busy copy with a working cancel option', async () => {
    const user = userEvent.setup()
    const cancelDocTask = vi.fn(async () => {})
    stubApi({
      listConversations: vi.fn(async () => []),
      listMessages: vi.fn(async () => []),
      getRuntimeStatus: vi.fn(async () => runningStatus),
      listDocuments: vi.fn(async () => [doc()]),
      createConversation: vi.fn(async () => ({
        id: 'c1',
        title: 'New chat',
        createdAt: '2026-06-11T00:00:00Z',
        updatedAt: '2026-06-11T00:00:00Z',
        modelId: null,
        mode: 'chat' as const,
        scopeDocumentIds: null,
        collectionId: null,
        scope: null
      })),
      sendChatMessage: vi.fn(async () => {
        throw new Error(DOC_TASK_BUSY_MESSAGE)
      }),
      onToken: vi.fn(() => () => {}),
      onReasoning: vi.fn(() => () => {}),
      onScopeNotice: vi.fn(() => () => {}),
      cancelDocTask
    })
    render(
      <ToastProvider>
        <ChatScreen onNavigate={() => {}} />
      </ToastProvider>
    )

    const input = await screen.findByPlaceholderText('Message…')
    await user.type(input, 'hello')
    await user.click(screen.getByRole('button', { name: /^send$/i }))

    expect(await screen.findByText(new RegExp(DOC_TASK_BUSY_MESSAGE.slice(0, 30)))).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /cancel document task/i }))
    expect(cancelDocTask).toHaveBeenCalled()
    // The banner clears once the task was cancelled.
    await waitFor(() =>
      expect(screen.queryByText(new RegExp(DOC_TASK_BUSY_MESSAGE.slice(0, 30)))).not.toBeInTheDocument()
    )
  })
})
